easy_admin:
    entities:
        User:
            class: App\Entity\User
#            export_path: '%kernel.project_dir/var/export/user'
            password_encoding: { algorithm: 'bcrypt', cost: 12 }